from __future__ import annotations

import subprocess
import tempfile
import os

from app.models.circuit_ir import AnalysisType, CircuitIR


# Map CircuitIR component types → SPICE element letters
SPICE_PREFIX: dict[str, str] = {
    "resistor": "R",
    "capacitor": "C",
    "inductor": "L",
    "diode": "D",
    "transistor": "Q",
    "mosfet": "M",
    "bjt": "Q",
    "ic": "X",
    "voltage_regulator": "X",
    "opamp": "X",
    "crystal": "X",
    "connector": "X",
    "led": "D",
    "switch": "S",
    "fuse": "R",
    "transformer": "T",
}

# Pin order for SPICE element lines
SPICE_PIN_ORDER: dict[str, list[str]] = {
    "resistor": ["1", "2"],
    "capacitor": ["1", "2"],
    "inductor": ["1", "2"],
    "diode": ["A", "K"],
    "led": ["A", "K"],
    "transistor": ["B", "C", "E"],
    "bjt": ["B", "C", "E"],
    "mosfet": ["G", "D", "S"],
    "voltage_regulator": ["IN", "OUT", "GND"],
    "opamp": ["IN+", "IN-", "V+", "V-", "OUT"],
}


class ExportService:
    def ir_to_spice(self, circuit: CircuitIR, analysis_type: AnalysisType = "dc") -> str:
        lines = [
            f"* {circuit.name}",
            f"* Generated by CircuitMind",
            f"* {circuit.metadata.description}",
            "",
        ]

        for comp in circuit.components:
            prefix = SPICE_PREFIX.get(comp.type, "X")
            pin_order = SPICE_PIN_ORDER.get(comp.type, sorted(comp.pins.keys()))
            nets = [comp.pins.get(pin, "0") for pin in pin_order]
            net_str = " ".join(nets) if nets else "0"

            if comp.type in ("resistor", "capacitor", "inductor"):
                lines.append(f"{prefix}{comp.id} {net_str} {comp.value}")
            elif comp.type in ("diode", "led"):
                model = comp.part_number or "1N4148"
                lines.append(f"{prefix}{comp.id} {net_str} {model}")
            elif comp.type in ("transistor", "bjt"):
                model = comp.part_number or "2N2222"
                lines.append(f"{prefix}{comp.id} {net_str} {model} NPN")
            elif comp.type == "mosfet":
                model = comp.part_number or "IRF540"
                lines.append(f"{prefix}{comp.id} {net_str} {model} NMOS")
            else:
                # Subcircuit (IC, voltage regulator, opamp, etc.)
                model = comp.part_number or comp.value.replace("-", "_").replace(".", "_")
                lines.append(f"X{comp.id} {net_str} {model}")

        lines.append("")

        # Add ideal voltage sources for power nets
        for net in circuit.nets:
            if net.type == "power" and net.voltage is not None:
                safe_name = net.name.replace("-", "_").replace("+", "P")
                lines.append(f"V_{safe_name} {net.name} 0 DC {net.voltage}")

        lines.append("")

        # Analysis statement
        if analysis_type == "dc":
            lines.append(".op")
        elif analysis_type == "ac":
            lines.append(".ac dec 10 1 1MEG")
        elif analysis_type == "transient":
            lines.append(".tran 1us 1ms")

        lines.append(".end")
        return "\n".join(lines)

    def ir_to_kicad_netlist(self, circuit: CircuitIR) -> str:
        """Generate KiCad netlist format via SKiDL Python script."""
        script = self._generate_skidl_script(circuit)

        with tempfile.TemporaryDirectory() as tmpdir:
            script_path = os.path.join(tmpdir, "circuit.py")
            netlist_path = os.path.join(tmpdir, "circuit.net")

            with open(script_path, "w") as f:
                f.write(script)

            try:
                result = subprocess.run(
                    ["python", script_path],
                    capture_output=True,
                    text=True,
                    timeout=30,
                    cwd=tmpdir,
                )
                if result.returncode == 0 and os.path.exists(netlist_path):
                    with open(netlist_path) as f:
                        return f.read()
                return f"* SKiDL error:\n{result.stderr}"
            except FileNotFoundError:
                return "* SKiDL/Python not available in this environment."

    def _generate_skidl_script(self, circuit: CircuitIR) -> str:
        lines = [
            "from skidl import *",
            "",
            f"# {circuit.name} — Generated by CircuitMind",
            "",
            "# Nets",
        ]

        net_var_map: dict[str, str] = {}
        for net in circuit.nets:
            safe = self._safe_var(net.name)
            net_var_map[net.name] = safe
            if net.name.upper() == "GND":
                lines.append(f"{safe} = Net('GND')")
            elif net.name.upper() in ("VCC", "VDD", "VIN", "VOUT"):
                lines.append(f"{safe} = Net('{net.name}')")
            else:
                lines.append(f"{safe} = Net('{net.name}')")

        lines.append("")
        lines.append("# Components")

        for comp in circuit.components:
            lib = self._map_kicad_lib(comp.type)
            sym = self._map_kicad_symbol(comp)
            fp = self._map_kicad_footprint(comp)
            lines.append(f"{comp.id} = Part('{lib}', '{sym}', footprint='{fp}', dest=TEMPLATE)")
            for pin, net_name in comp.pins.items():
                net_var = net_var_map.get(net_name, self._safe_var(net_name))
                lines.append(f"{comp.id}['{pin}'] += {net_var}")

        lines.append("")
        lines.append("generate_netlist()")
        return "\n".join(lines)

    def _safe_var(self, name: str) -> str:
        return name.replace("-", "_").replace("+", "P").replace("/", "_").replace(".", "_")

    def _map_kicad_lib(self, component_type: str) -> str:
        mapping = {
            "resistor": "Device",
            "capacitor": "Device",
            "inductor": "Device",
            "diode": "Device",
            "led": "Device",
            "transistor": "Device",
            "bjt": "Device",
            "mosfet": "Device",
            "ic": "Device",
            "voltage_regulator": "Regulator_Linear",
            "opamp": "Amplifier_Operational",
            "crystal": "Device",
            "connector": "Connector",
        }
        return mapping.get(component_type, "Device")

    def _map_kicad_symbol(self, comp: type) -> str:  # type: ignore[override]
        mapping = {
            "resistor": "R",
            "capacitor": "C",
            "inductor": "L",
            "diode": "D",
            "led": "LED",
            "transistor": "Q_NPN_BCE",
            "bjt": "Q_NPN_BCE",
            "mosfet": "Q_NMOS_GDS",
            "voltage_regulator": "AMS1117-3.3",
            "opamp": "LM741",
            "crystal": "Crystal",
            "connector": "Conn_01x02",
        }
        if hasattr(comp, "part_number") and comp.part_number:
            return comp.part_number
        return mapping.get(comp.type, "IC")

    def _map_kicad_footprint(self, comp: type) -> str:  # type: ignore[override]
        pkg = comp.package if hasattr(comp, "package") else "0402"
        footprint_map = {
            "0402": "Resistor_SMD:R_0402_1005Metric",
            "0603": "Resistor_SMD:R_0603_1608Metric",
            "0805": "Resistor_SMD:R_0805_2012Metric",
            "SOT-23": "Package_TO_SOT_SMD:SOT-23",
            "SOIC-8": "Package_SO:SOIC-8_3.9x4.9mm_P1.27mm",
            "DIP-8": "Package_DIP:DIP-8_W7.62mm",
            "TO-92": "Package_TO_SOT_THT:TO-92_Inline",
        }
        return footprint_map.get(pkg, f"Resistor_SMD:R_{pkg}")
